version: "3"

volumes:
  mongo-data:

services:
  app:
    build:
      context: .
    restart: unless-stopped
    command:
      - bash
      - -c
      - "go get && gow -e=go,env,html run main.go"
    logging:
      options:
        max-size: "500k"
        max-file: "2"
    environment:
      MONGO_HOST: ${MONGO_HOST:-mongo:27017}
      MONGO_USERNAME: ${MONGO_USERNAME:-root}
      MONGO_PASSWORD: ${MONGO_PASSWORD:-farofa}
    volumes:
      - ./:/go/src/app
    ports:
      - ${FORWARD_APP_PORT:-8080}:8080
  mongo:
    image: mongo
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE:-headlinesbr}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME:-root}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD:-farofa}

  mongo-express:
    image: mongo-express
    restart: unless-stopped
    ports:
      - ${FORWARD_MONGO_EXPRESS_PORT:-8081}:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USERNAME:-root}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD:-farofa}
