version: "3"

volumes:
  mongo-model:

services:
  app:
    build:
      context: .
    restart: "no"
    command:
      - bash
      - -c
      - "go get && gow -e=go,env,html run main.go"
    logging:
      options:
        max-size: "500k"
        max-file: "2"
    environment:
      SERVER_PORT: ${SERVER_PORT:-8080}
      MONGO_DATABASE: ${MONGO_DATABASE:-headlinesbr}
      MONGO_HOST: ${MONGO_HOST:-mongo:27017}
      MONGO_USERNAME: ${MONGO_USERNAME}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - ./:/go/src/app
    ports:
      - ${FORWARD_APP_PORT:-8080}:8080
    depends_on:
      - mongo
  mongo:
    image: mongo
    restart: "no"
    volumes:
      - mongo-model:/model/db
    logging:
      options:
        max-size: "500k"
        max-file: "2"
    ports:
      - ${MONGO_FORWARD_PORT:-0}:27017
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}

  mongo-express:
    image: mongo-express
    restart: "no"
    logging:
      options:
        max-size: "500k"
        max-file: "2"
    ports:
      - ${FORWARD_MONGO_EXPRESS_PORT:-8081}:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD}
